#!/bin/sh

curl -X POST "http://localhost:8090/api/resources/zones/4c47c579-7558-454b-bcac-8662bcafb4f6/records/" \
   -H 'Content-Type: application/json' \
   -d '{"fqdn":"green.cod.","type":1,"value":"192.168.0.42"}'
